app:
  app-name: MachineLearning
  env: local

kafka-spout:
  host: 10.100.100.105 # Kafka IP 需要修改
  port: 9092
  topic: iot-kafka # Kafka Topic 需要修改
  group-id: strom-consumer
  auto-offset-reset: earliest

model-server:
  host: localhost # 模型部署在那个host，需要修改
  port: 80
  model-url: http://localhost:5000/api/predict  # 模型预测的URL，需要修改为 IP:port/api/predict 格式
  model-config-url: http://localhost:5000/api/load_model_config # 模型预测的URL，需要修改 IP:port/api/load_model_config 格式

control-server:
  host: localhost # 反向控制的host，需要修改
  port: 80
  control-url: https://localhost:80 # 反向控制的URL，需要IOThub提供


