app:
  app-name: MachineLearning
  env: local

kafka-spout:
  host: 10.100.100.105
  port: 9092
  topic: iot-kafka
  group-id: strom-consumer
  auto-offset-reset: earliest

model-server:
  host: localhost
  port: 80
  model-url: http://localhost:5000/api/predict
  model-config-url: http://localhost:5000/api/load_model_config

control-server:
  host: localhost
  port: 80
  control-url: https://localhost:80


